version: 0.2
env:
  variables:
    REPOSITORY_URI: ""
    LC_CTYPE: "C.UTF-8"
    ENV_BUCKET: ""
    ENV_FILE: ""
    TARGETS: ""
    DISTRIBUTION_ID: ""
    AWS_REACT_APP_BUCKET_NAME: ""
phases:
  pre_build:
    commands:
      - echo Add env file
      - aws s3 cp s3://${ENV_BUCKET}/${ENV_FILE} .env
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync public/ s3://${AWS_REACT_APP_BUCKET_NAME}
