version: 0.2
env:
  variables:
    REPOSITORY_URI: ""
    LC_CTYPE: "C.UTF-8"
    ENV_BUCKET: ""
    ENV_FILE: ""
    TARGETS: ""
    DISTRIBUTION_ID: ""

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
