version: 0.2
env:
  variables:
    REPOSITORY_URI: ""
    LC_CTYPE: "C.UTF-8"
    ENV_BUCKET: ""
    ENV_FILE: ""
    TARGETS: ""
    DISTRIBUTION_ID: ""

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Add env file 
      - aws s3 cp s3://${ENV_BUCKET}/${ENV_FILE} .env
  build:
    commands:
      - echo Build started on `date`
      - npm run lint
      - npm run build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
